// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Portal.Infrastructure;
using System;

namespace Portal.Infrastructure.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20180523074636_Add picture To Entity")]
    partial class AddpictureToEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Portal.core.Media.Picture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AltAttribute");

                    b.Property<long?>("ContentId");

                    b.Property<bool>("IsNew");

                    b.Property<string>("MimeType");

                    b.Property<byte[]>("PictureBinary");

                    b.Property<string>("SeoFilename");

                    b.Property<string>("TitleAttribute");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("Portal.core.News.Content", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body");

                    b.Property<long>("GroupId");

                    b.Property<bool>("Hidden");

                    b.Property<int>("Hit");

                    b.Property<bool>("IsAllowedComment");

                    b.Property<string>("Lead");

                    b.Property<decimal>("Rate");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("Portal.core.News.Group", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<bool>("DisplayInMain");

                    b.Property<bool>("IsPrivate");

                    b.Property<long?>("ParentId");

                    b.Property<bool>("PictureID");

                    b.Property<int>("Priority");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Portal.core.Media.Picture", b =>
                {
                    b.HasOne("Portal.core.News.Content")
                        .WithMany("Pictures")
                        .HasForeignKey("ContentId");
                });

            modelBuilder.Entity("Portal.core.News.Content", b =>
                {
                    b.HasOne("Portal.core.News.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
