// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portal.Standard.Infrastructure;

namespace Portal.Standard.Infrastructure.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    partial class PortalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Portal.Standard.Core.Media.Picture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AltAttribute");

                    b.Property<bool>("IsNew");

                    b.Property<string>("MimeType");

                    b.Property<byte[]>("PictureBinary");

                    b.Property<string>("SeoFilename");

                    b.Property<string>("TitleAttribute");

                    b.HasKey("Id");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("Portal.Standard.Core.News.ContentPicture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ContentId");

                    b.Property<int>("DisplayOrder");

                    b.Property<long>("PictureId");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("PictureId");

                    b.ToTable("ContentPictures");
                });

            modelBuilder.Entity("Portal.Standard.Core.News.Group", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<bool>("DisplayInMain");

                    b.Property<bool>("IsPrivate");

                    b.Property<long?>("ParentId");

                    b.Property<bool>("PictureID");

                    b.Property<int>("Priority");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "",
                            DisplayInMain = true,
                            IsPrivate = false,
                            PictureID = false,
                            Priority = 0,
                            Title = "ورزشی"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "",
                            DisplayInMain = true,
                            IsPrivate = false,
                            PictureID = false,
                            Priority = 0,
                            Title = "فن آوری اطلاعات"
                        });
                });

            modelBuilder.Entity("Portal.core.News.Content", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body");

                    b.Property<long>("GroupId");

                    b.Property<bool>("Hidden");

                    b.Property<int>("Hit");

                    b.Property<bool>("IsAllowedComment");

                    b.Property<string>("Lead");

                    b.Property<decimal>("Rate");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("Portal.Standard.Core.News.ContentPicture", b =>
                {
                    b.HasOne("Portal.core.News.Content", "Content")
                        .WithMany("ContentPictures")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Portal.Standard.Core.Media.Picture", "Picture")
                        .WithMany()
                        .HasForeignKey("PictureId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Portal.core.News.Content", b =>
                {
                    b.HasOne("Portal.Standard.Core.News.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
